services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres_rbac'
    environment:
      - 'POSTGRES_DB=rbac-demo'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    ports:
      - '12003:5432'